global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram1'

receivers:
- name: telegram1
  telegram_configs:
  - send_resolved: true
    bot_token: '(токен бота)'
    chat_id: 532301590
    parse_mode: HTML

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']
